### ISSUE TITLE
Default Unmarshalling of Number Type (timestamp) as Float64 but required in int64

### ISSUE THREAD

**Issue by himgang** [btnguyen2k/godynamo#283]
in stmt.go file, method: func (r *ResultResultSet) init() *ResultResultSet
we are unmarshalling values using 
var value interface{}
_ = attributevalue.Unmarshal(av, &value)
In case of timestamps in my data models we are using int64. But the default behaviour is that the value is loaded as float64.
Is there anyway to handle or override in the driver this ?
Test Item I am using
{
            "updated_at": {
                "N": "1734630621"
            },
            "created_at": {
                "N": "1734630621"
            },
            "id": {
                "S": "1"
            }
}
I can make changes and raise PR but not sure how can we fix this while using attributevalue.Unmarshal

**Comment by himgang** [comment]
@miyamo2 Please see if you can suggest something here.

**Comment by himgang** [comment]
its a limitation from aws go sdk side, from what I understood we can't handle that on this driver.

**Comment by miyamo2** [comment]
I think the one way to deal with this is to add proprietary extended PartiQL syntax, since `attributevalue.Unmarshal` is done in the lifecycle before receiving the value to be scanned from the user.
And it would be possible to achieve this by casting the unmarshalled value based on that syntax.
```go
var tmp, value interface{}
_ = attributevalue.Unmarshal(av, &tmp)

if asInt64 {
    switch tmp := tmp.(type) {
    case float64:
        value = int64(tmp)
    }
}
```

However, this would be much easier to handle in userland, for both the maintainer and the user.
One example would be to implement `sql.Scanner` on defined type.
(Or maybe you can find a utility like this as OSS.)
```go
type MyInt64 int64

func (m *MyInt64) Scan(value any) {
    switch value := value.(type) {
    case float64:
        *m = MyInt64(int64(value))
    }
    return
}
```

**Comment by himgang** [comment]
@miyamo2 Thanks for the suggestions, I was primarily exploring second one. But would definitely try first one as well.
